### ISSUE TITLE
E2EE advisory

### ISSUE THREAD

**Issue by haskell-monad** [neilalexander/seaglass#131]
How many people (1000 people?10000 people?) are supported in E2E encryption group chat? As far as I know, when using the signal protocol group chat, when the number of people increases, the performance will drop dramatically.

**Comment by aaronraimist** [comment]
There is no limit but the first message you send in a large group can be kind of slow. `#megolm:matrix.org` is an example of a largeish E2EE room. I don't know of any larger public E2EE but maybe they exist.

Anyway this isn't a great place to ask questions about Matrix. `#matrix:matrix.org` would be a good place to ask instead of opening issues (which are meant to be bugs or feature requests).
