### ISSUE TITLE
Message entry field doesn't grow with multiline input

### ISSUE THREAD

**Issue by neilalexander** [neilalexander/seaglass#45]
## Specifications

  - Seaglass Version: Any
  - macOS Version: 10.13.6

## Expected Behavior

The message entry field should grow vertically with multiline text.

## Actual Behavior

It doesn't.

## Steps to Reproduce the Problem

  1. Alt-Enter when entering text.

**Comment by aaronraimist** [comment]
![screen shot 2018-08-31 at 1 23 53 pm](https://user-images.githubusercontent.com/5855073/44929600-3769b280-ad21-11e8-9084-2db4c37bc775.png)
![screen shot 2018-08-31 at 1 24 02 pm](https://user-images.githubusercontent.com/5855073/44929601-389adf80-ad21-11e8-836d-507ada7ccc8e.png)

Is it expected that a multi line message with no gap between them would show up in other clients as being on the same line?

Also I'd love to get shift+enter as well since that is what I'm used to from Riot.

**Comment by neilalexander** [comment]
Indeed that is not expected behaviour, must be something in the Markdown parser. I'll take a look at that.
